updated listip and pingtest to support CIDR notation

diff --git a/src/listip b/src/listip
--- a/src/listip
+++ b/src/listip
@@ -3,13 +3,26 @@
 ( if [[ "$1" =~ \-.*h.* ]]; then
 	exit 3
 fi
-if [[ ! ${@: -1} =~ ^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$ ]] \
+if [[ "$1" =~ \-.*c.* ]]; then
+	if [[ ! ${@: -1} =~ ^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\/([0-9][0-9]?)$ ]]; then
+		echo -e "Invalid IP address ${@: -1}"
+		exit 3
+	fi
+	if [[ ! ${@: -1} =~ "/" ]]; then
+		echo -e "Please use CIDR notation when using '-c'"
+		exit 3
+	fi
+	IFS="/" read -ra ADDR <<< ${@: -1} 
+	lowip="${ADDR[0]}"
+	highip=(`ipcalc "${@: -1}" | grep Max | awk '{print $2}'`)
+elif [[ ! ${@: -1} =~ ^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$ ]] \
 	|| [[ ! ${@: -2:1} =~ ^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$ ]]; then
 	echo -e "Invalid IP address"
 	exit 3
+else
+	lowip=${@: -2:1}
+	highip=${@: -1}
 fi
-lowip=${@: -2:1}
-highip=${@: -1}
 low=(`echo "$lowip" | awk '{split($lowip,a,"."); print a[1]" "a[2]" "a[3]" "a[4]}'`)
 high=(`echo "$highip" | awk '{split($highip,a,"."); print a[1]" "a[2]" "a[3]" "a[4]}'`)
 max=255
